#!/bin/sh

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

cd "${CURRENT_DIR}"

chmod -R 0700 tools mount

mkdir -p game

cd "${CURRENT_DIR}"/tools

./squashfuse "${CURRENT_DIR}"/tools/fs "${CURRENT_DIR}"/game
